export interface ExperienceData {
  slug: string;
  company: string;
  role: string;
  startDate: string;
  endDate: string;
  location: string;
  brief: string;
  bullets: string[];
  logoPlaceholder: string;
  logo?: string; // set this when you provide logo assets: e.g. "/logos/wasserman.png"
}

export const experiences: ExperienceData[] = [
  {
    slug: "the-team",
    company: "THE·TEAM",
    role: "Brand Strategy & Consulting Intern",
    startDate: "2026-01-01",
    endDate: "2026-05-01",
    location: "Chicago, IL",
    brief: "Analyzed the sponsorship landscape across 181 teams in 7 pro sports leagues and delivered competitive intelligence to inform client investment decisions.",
    bullets: [
      "Led a two-person team to analyze the sponsorship landscape across 181 teams in seven professional sports leagues.",
      "Delivered competitive intelligence to inform client investment decisions effectively.",
      "Produced 13 weekly newsletters for clients, ensuring they stayed updated on partnership developments.",
      "Assisted in strategic planning for AI integration within our internal team, pitching to senior directors, and increasing team productivity.",
    ],
    logoPlaceholder: "T",
    logo: "/logos/the-team.jpeg",
  },
  {
    slug: "oregon-founders-club",
    company: "Oregon Founders Club",
    role: "Director of Professional Development",
    startDate: "2025-05-01",
    endDate: "2026-05-01",
    location: "Eugene, OR",
    brief: "Directed outreach strategies to secure guest speakers and coordinated the club's inaugural industry site visit.",
    bullets: [
      "Directed outreach strategies to secure guest speakers, enhancing professional development opportunities for club members.",
      "Coordinated the club's inaugural site visit with Pipeworks, fostering valuable industry connections.",
      "Cultivated relationships with industry professionals to enrich the club's educational offerings.",
    ],
    logoPlaceholder: "O",
    logo: "/logos/ofc.jpeg",
  },
  {
    slug: "ameriprise",
    company: "Ameriprise Financial",
    role: "Financial Advising Externship",
    startDate: "2025-08-01",
    endDate: "2025-09-01",
    location: "Los Angeles, CA",
    brief: "Analyzed client portfolios and researched market trends to support advisor decision-making and investment recommendations.",
    bullets: [
      "Analyzed diverse client portfolios, applying strategies in equities, bonds, and mutual funds for optimal long-term performance.",
      "Researched market trends to enhance advisor decision-making and improve client presentations.",
      "Evaluated fund performance using financial software, generating insights to support investment recommendations.",
    ],
    logoPlaceholder: "A",
    logo: "/logos/ameriprise.jpeg",
  },
  {
    slug: "entertainment-psychology",
    company: "Entertainment Psychology Inc",
    role: "Marketing Intern",
    startDate: "2025-06-01",
    endDate: "2025-07-01",
    location: "Los Angeles, CA",
    brief: "Led content creation strategy targeting 1,000 new digital media subscribers using trend-based content across Instagram, TikTok, and LinkedIn.",
    bullets: [
      "Led weekly content creation by pitching four topics to support the goal of gaining 1,000 new digital media subscribers.",
      "Collaborated on marketing campaigns using Slack, Drive, and Teams to ensure brand consistency and meet publishing deadlines.",
      "Boosted engagement through trend-based content creation with Canva and CapCut, enhancing growth on Instagram, TikTok, and LinkedIn.",
    ],
    logoPlaceholder: "E",
    logo: "/logos/ep.jpeg",
  },
  {
    slug: "oregon-innovation-s3",
    company: "Oregon Innovation Challenge",
    role: "Funded Fellow, Season 3",
    startDate: "2025-04-01",
    endDate: "2025-07-01",
    location: "Eugene, OR",
    brief: "One of 30 ventures to secure funding out of 300+ student-led startups in a competitive 12-week accelerator.",
    bullets: [
      "Selected as a Funded Fellow in the highly competitive Oregon Innovation Challenge.",
      "12-week venture accelerator that began with over 300 student-led startups.",
      "Only 80 teams advanced to pitch at Demo Day. Just 30 ventures secured funding.",
      "Our team was one of them.",
    ],
    logoPlaceholder: "O",
    logo: "/logos/oic.jpeg",
  },
  {
    slug: "veo-strip",
    company: "Veo Strip",
    role: "Field Marketing Intern",
    startDate: "2025-01-01",
    endDate: "2025-06-01",
    location: "Eugene, OR",
    brief: "Developed go-to-market strategies and engaged 1,000+ marathon attendees with live demos, achieving 100+ trial conversions.",
    bullets: [
      "Collaborated with interns to research market trends in Eugene, focusing on promoting the Veo Strip.",
      "Developed actionable go-to-market strategies, establishing a framework for sales approaches.",
      "Managed a CRM of 40+ influencers, enhancing outreach efficiency through segmentation.",
      "Engaged over 1,000 marathon attendees with live demos, achieving 100+ trial conversions.",
    ],
    logoPlaceholder: "V",
    logo: "/logos/veo-strip.jpeg",
  },
  {
    slug: "emerald-media",
    company: "Emerald Media Group",
    role: "Photojournalist",
    startDate: "2024-05-01",
    endDate: "2025-04-01",
    location: "United States",
    brief: "Captured portraits and sporting event photography weekly for publication in online articles and newspapers.",
    bullets: [
      "Took portraits and sporting event pictures weekly for publication in online articles and newspapers.",
    ],
    logoPlaceholder: "E",
    logo: "/logos/emerald-media.jpeg",
  },
  {
    slug: "nx1",
    company: "NX1",
    role: "Co-Founder",
    startDate: "2024-03-01",
    endDate: "2025-12-01",
    location: "Eugene, OR",
    brief: "Co-founded an NIL education platform helping student-athletes understand and monetize their rights, growing it through competitive startup programs and a podcast built to earn trust at scale.",
    bullets: [
      "Co-founded an NIL education platform giving student-athletes clear, practical guidance on their money-making rights and how to act on them.",
      "Advanced through the Oregon Innovation Challenge as a Season 2 finalist, then returned in Season 3 and secured funding as one of 30 ventures selected from 300+ student-led startups.",
      "Launched the NX1 Podcast as a deliberate growth strategy, documenting the behind-the-scenes reality of college sports to build brand awareness and credibility across campus.",
      "Used the podcast to cultivate relationships with athletes, coaches, and industry figures, creating a network that directly supported our go-to-market efforts.",
      "Turned campus visibility built through OIC and the podcast into the trust foundation needed to launch a paid service in the NIL space.",
    ],
    logoPlaceholder: "N",
    logo: "/logos/nx1.jpeg",
  },
  {
    slug: "sales-club",
    company: "Oregon Sales Club",
    role: "Competitive Member",
    startDate: "2024-01-01",
    endDate: "2026-05-01",
    location: "Eugene, OR",
    brief: "Competed in regional and national sales competitions, developing consultative selling, client prospecting, and professional persuasion skills through structured practice and live competition.",
    bullets: [
      "Competed in regional and national sales competitions, applying consultative selling techniques under real-world pressure with experienced judges from industry.",
      "Developed client prospecting, objection handling, and needs-based selling skills through structured practice sessions and peer critique.",
      "Participated in professional development workshops with practitioners covering negotiation, presentation strategy, and deal structure.",
      "Sharpened the ability to read a room, build rapport quickly, and adapt messaging to different decision-makers — skills directly applicable to brand strategy pitches and client work.",
    ],
    logoPlaceholder: "S",
    logo: "/logos/sales-club.jpeg",
  },
  {
    slug: "sports-illustrated",
    company: "Sports Illustrated",
    role: "Photographer, Duck Digest",
    startDate: "2024-03-01",
    endDate: "2024-04-01",
    location: "Eugene, OR",
    brief: "Captured and edited 200+ photos in strict 20-minute intervals, delivering ready-to-publish images for timely articles.",
    bullets: [
      "Captured 200 photos in 20-minute allowed intervals, editing photos down to 40 within a couple of hours, ready to be sent to writers for timely posts.",
    ],
    logoPlaceholder: "S",
    logo: "/logos/si.jpeg",
  },
  {
    slug: "eugene-emeralds",
    company: "Eugene Emeralds Baseball",
    role: "Promotions Crew",
    startDate: "2024-04-01",
    endDate: "2024-06-01",
    location: "Eugene, OR",
    brief: "Coordinated 7+ in-game promotion events within tight time slots throughout professional baseball game nights.",
    bullets: [
      "Coordinated with a team to run over 7 promotion events within 1-minute 30-second time slots throughout a game night.",
    ],
    logoPlaceholder: "E",
    logo: "/logos/eugene-emeralds.jpeg",
  },
  {
    slug: "oregon-innovation-s2",
    company: "Oregon Innovation Challenge",
    role: "Business Pitcher Finalist, Season 2",
    startDate: "2024-01-01",
    endDate: "2024-07-01",
    location: "Eugene, OR",
    brief: "Developed and iterated a self-directed venture over 12 weeks, advancing as a finalist in a competitive startup competition.",
    bullets: [
      "Engaged in workshops led by seasoned entrepreneurs, enhancing skills in customer discovery and prototyping.",
      "Developed a self-directed venture over 12 weeks, iterating based on valuable feedback received.",
    ],
    logoPlaceholder: "O",
    logo: "/logos/oic.jpeg",
  },
  {
    slug: "oregon-pit-crew",
    company: "Oregon Pit Crew",
    role: "Photographer & Videographer",
    startDate: "2023-10-01",
    endDate: "2024-09-01",
    location: "Eugene, OR",
    brief: "Filmed and edited content for Oregon Athletics including a Black History Month video that reached 1M+ views on the Jumbotron and social media.",
    bullets: [
      "Filmed and edited a Black History Month video with the Basketball Team, making it onto the Jumbotron and Oregon Athletic socials reaching over a million views.",
    ],
    logoPlaceholder: "O",
    logo: "/logos/oregon-pit-crew.jpeg",
  },
];
